site_name: napkin

# theme: bootstrap

theme:
    name: mkdocs
    nav_style: light

extra_css:
    - css/extra.css

markdown_extensions:
    - attr_list

nav:
  - C1:
    - context: team_comms/1_context.md
    - onboarding: team_comms/2_onboarding.md
    - channels: team_comms/3_channels.md
    - messaging: team_comms/4_messaging.md
    - integrations: team_comms/5_integrations.md
    - voip: team_comms/6_voip.md
    - automation: team_comms/7_automation.md
    - search: team_comms/8_search.md
    - posts: team_comms/9_posts.md
    - lorem: team_comms/10_lorem.md
    - lorem: team_comms/11_lorem.md
    - lorem: team_comms/12_lorem.md
    - lorem: team_comms/13_lorem.md
    - lorem: team_comms/14_lorem.md
    - lorem: team_comms/15_lorem.md
    - lorem: team_comms/16_lorem.md
    - lorem: team_comms/17_lorem.md
    - lorem: team_comms/18_lorem.md
    - lorem: team_comms/19_lorem.md
    - lorem: team_comms/20_lorem.md
  - C2:
    - lorem: project_mgmt/1_lorem.md
    - lorem: project_mgmt/2_lorem.md
    - lorem: project_mgmt/3_lorem.md
    - lorem: project_mgmt/4_lorem.md
    - lorem: project_mgmt/5_lorem.md
    - lorem: project_mgmt/6_lorem.md
    - lorem: project_mgmt/7_lorem.md
    - lorem: project_mgmt/8_lorem.md
    - lorem: project_mgmt/9_lorem.md
    - lorem: project_mgmt/10_lorem.md
    - lorem: project_mgmt/11_lorem.md
    - lorem: project_mgmt/12_lorem.md
    - lorem: project_mgmt/13_lorem.md
    - lorem: project_mgmt/14_lorem.md
    - lorem: project_mgmt/15_lorem.md
    - lorem: project_mgmt/16_lorem.md
    - lorem: project_mgmt/17_lorem.md
    - lorem: project_mgmt/18_lorem.md
    - lorem: project_mgmt/19_lorem.md
    - lorem: project_mgmt/20_lorem.md
  - C3:
    - lorem: creative/1_creative.md
    - lorem: creative/2_creative.md
    - lorem: creative/3_creative.md
    - lorem: creative/4_creative.md
    - lorem: creative/5_creative.md
    - lorem: creative/6_creative.md
    - lorem: creative/7_creative.md
    - lorem: creative/8_creative.md
    - lorem: creative/9_creative.md
    - lorem: creative/10_creative.md
    - lorem: creative/11_creative.md
    - lorem: creative/12_creative.md
    - lorem: creative/13_creative.md
    - lorem: creative/14_creative.md
    - lorem: creative/15_creative.md
    - lorem: creative/16_creative.md
    - lorem: creative/17_creative.md
    - lorem: creative/18_creative.md
    - lorem: creative/19_creative.md
    - lorem: creative/20_creative.md
  - C4:
    - lorem: graphics/1_graphics.md
    - lorem: graphics/2_graphics.md
    - lorem: graphics/3_graphics.md
    - lorem: graphics/4_graphics.md
    - lorem: graphics/5_graphics.md
    - lorem: graphics/6_graphics.md
    - lorem: graphics/7_graphics.md
    - lorem: graphics/8_graphics.md
    - lorem: graphics/9_graphics.md
    - lorem: graphics/10_graphics.md
    - lorem: graphics/11_graphics.md
    - lorem: graphics/12_graphics.md
    - lorem: graphics/13_graphics.md
    - lorem: graphics/14_graphics.md
    - lorem: graphics/15_graphics.md
    - lorem: graphics/16_graphics.md
    - lorem: graphics/17_graphics.md
    - lorem: graphics/18_graphics.md
    - lorem: graphics/19_graphics.md
    - lorem: graphics/20_graphics.md
  - C5:
    - lorem: video/1_video.md
    - lorem: video/2_video.md
    - lorem: video/3_video.md
    - lorem: video/4_video.md
    - lorem: video/5_video.md
    - lorem: video/6_video.md
    - lorem: video/7_video.md
    - lorem: video/8_video.md
    - lorem: video/9_video.md
    - lorem: video/10_video.md
    - lorem: video/11_video.md
    - lorem: video/12_video.md
    - lorem: video/13_video.md
    - lorem: video/14_video.md
    - lorem: video/15_video.md
    - lorem: video/16_video.md
    - lorem: video/17_video.md
    - lorem: video/18_video.md
    - lorem: video/19_video.md
    - lorem: video/20_video.md
  - C6:
    - lorem: content_mgmt/1_lorem.md
    - lorem: content_mgmt/2_lorem.md
    - lorem: content_mgmt/3_lorem.md
    - lorem: content_mgmt/4_lorem.md
    - lorem: content_mgmt/5_lorem.md
    - lorem: content_mgmt/6_lorem.md
    - lorem: content_mgmt/7_lorem.md
    - lorem: content_mgmt/8_lorem.md
    - lorem: content_mgmt/9_lorem.md
    - lorem: content_mgmt/10_lorem.md
    - lorem: content_mgmt/11_lorem.md
    - lorem: content_mgmt/12_lorem.md
    - lorem: content_mgmt/13_lorem.md
    - lorem: content_mgmt/14_lorem.md
    - lorem: content_mgmt/15_lorem.md
    - lorem: content_mgmt/16_lorem.md
    - lorem: content_mgmt/17_lorem.md
    - lorem: content_mgmt/18_lorem.md
    - lorem: content_mgmt/19_lorem.md
    - lorem: content_mgmt/20_lorem.md
  - C7:
    - lorem: webdev/1_webdev.md
    - lorem: webdev/2_webdev.md
    - lorem: webdev/3_webdev.md
    - lorem: webdev/4_webdev.md
    - lorem: webdev/5_webdev.md
    - lorem: webdev/6_webdev.md
    - lorem: webdev/7_webdev.md
    - lorem: webdev/8_webdev.md
    - lorem: webdev/9_webdev.md
    - lorem: webdev/10_webdev.md
    - lorem: webdev/11_webdev.md
    - lorem: webdev/12_webdev.md
    - lorem: webdev/13_webdev.md
    - lorem: webdev/14_webdev.md
    - lorem: webdev/15_webdev.md
    - lorem: webdev/16_webdev.md
    - lorem: webdev/17_webdev.md
    - lorem: webdev/18_webdev.md
    - lorem: webdev/19_webdev.md
    - lorem: webdev/20_webdev.md
  - C8:
    - lorem: data/1_data.md
    - lorem: data/2_data.md
    - lorem: data/3_data.md
    - lorem: data/4_data.md
    - lorem: data/5_data.md
    - lorem: data/6_data.md
    - lorem: data/7_data.md
    - lorem: data/8_data.md
    - lorem: data/9_data.md
    - lorem: data/10_data.md
    - lorem: data/11_data.md
    - lorem: data/12_data.md
    - lorem: data/13_data.md
    - lorem: data/14_data.md
    - lorem: data/15_data.md
    - lorem: data/16_data.md
    - lorem: data/17_data.md
    - lorem: data/18_data.md
    - lorem: data/19_data.md
    - lorem: data/20_data.md
